config/routes.rb
Rails.application.routes.draw do
  resources :thumbnails
  resources :portfolios
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/thumbnail.rb
class Thumbnail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
      @portfolio_item = Portfolio.all  
    end

    def new
     @portfolio_item = Portfolio.new 
    end

    def create
    
    end

    def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
        end
      end
     end


end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:title, :body)
    end
end

app/controllers/thumbnails_controller.rb
class ThumbnailsController < ApplicationController
  before_action :set_thumbnail, only: [:show, :edit, :update, :destroy]

  # GET /thumbnails
  # GET /thumbnails.json
  def index
    @thumbnails = Thumbnail.all
  end

  # GET /thumbnails/1
  # GET /thumbnails/1.json
  def show
  end

  # GET /thumbnails/new
  def new
    @thumbnail = Thumbnail.new
  end

  # GET /thumbnails/1/edit
  def edit
  end

  # POST /thumbnails
  # POST /thumbnails.json
  def create
    @thumbnail = Thumbnail.new(thumbnail_params)

    respond_to do |format|
      if @thumbnail.save
        format.html { redirect_to @thumbnail, notice: 'Thumbnail was successfully created.' }
        format.json { render :show, status: :created, location: @thumbnail }
      else
        format.html { render :new }
        format.json { render json: @thumbnail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thumbnails/1
  # PATCH/PUT /thumbnails/1.json
  def update
    respond_to do |format|
      if @thumbnail.update(thumbnail_params)
        format.html { redirect_to @thumbnail, notice: 'Thumbnail was successfully updated.' }
        format.json { render :show, status: :ok, location: @thumbnail }
      else
        format.html { render :edit }
        format.json { render json: @thumbnail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thumbnails/1
  # DELETE /thumbnails/1.json
  def destroy
    @thumbnail.destroy
    respond_to do |format|
      format.html { redirect_to thumbnails_url, notice: 'Thumbnail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thumbnail
      @thumbnail = Thumbnail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thumbnail_params
      params.require(:thumbnail).permit(:title, :body, :main_image, :thumb_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/thumbnails_helper.rb
module ThumbnailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scratch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/portfolios/index.html.erb
<h1>portfolio#index</h1>
<%@portfolio_item.each do |portfolio_items|%>
    <%r=portfolio_items.title%>
    <%=portfolio_items.thumb_image%>
    <%=portfolio_items.main_image%>
    <%=portfolio_items.body%>

    <hr>
<% end %>
  

app/views/portfolios/new.html.erb
<%= form_for(@portfolio_item) do |form| %>
 <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thumbnails/_form.html.erb
<%= form_with(model: thumbnail, local: true) do |form| %>
  <% if thumbnail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thumbnail.errors.count, "error") %> prohibited this thumbnail from being saved:</h2>

      <ul>
      <% thumbnail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :main_image %>
    <%= form.text_area :main_image %>
  </div>

  <div class="field">
    <%= form.label :thumb_image %>
    <%= form.text_area :thumb_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thumbnails/edit.html.erb
<h1>Editing Thumbnail</h1>

<%= render 'form', thumbnail: @thumbnail %>

<%= link_to 'Show', @thumbnail %> |
<%= link_to 'Back', thumbnails_path %>

app/views/thumbnails/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Thumbnail', new_thumbnail_path %>
<h1>Thumbnails</h1>

    <div>
      <em>Title</em>
      <em>Body</em>
      <em>Main image</em>
      <em>Thumb image</em>
    </div>

    
    <% @thumbnails.each do |thumbnail| %>
    <div>
        <%= link_to  thumbnail.title,thumbnail_path(thumbnail.id)%>  
        <em><%= thumbnail.title %></em>
        <em><%= thumbnail.body %></em>
        <em><%= thumbnail.main_image %></em>
        <em><%=image_tag thumbnail.thumb_image %></em>
        <em><%= link_to 'Show', thumbnail %></em>
        <em><%= link_to 'Edit', edit_thumbnail_path(thumbnail) %></em>
        <em><%= link_to 'Destroy', thumbnail, method: :delete, data: { confirm: 'Are you sure?' } %></em>
    </div>
    <% end %>
    

<br>

app/views/thumbnails/new.html.erb
<h1>New Thumbnail</h1>

<%= render 'form', thumbnail: @thumbnail %>

<%= link_to 'Back', thumbnails_path %>

app/views/thumbnails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @thumbnail.title %>
</p>

<p>
  <%= @thumbnail.body %>
</p>

<p>
  <%= image_tag @thumbnail.main_image %>
</p>

<p>
  <%=  @thumbnail.thumb_image %>
</p>

<%= link_to 'Edit', edit_thumbnail_path(@thumbnail) %> |
<%= link_to 'Back', thumbnails_path %>